### ISSUE TITLE
Request Review - Ruby Capstone Project, Setup Kanban Board

### ISSUE THREAD

**Issue by fickryiman** [fickryiman/Catalog-of-my-things#29]
GitHub project link: 
https://github.com/fickryiman/Catalog-of-my-things/projects/1

We have 3 people in our Team.

Team member #1 : https://github.com/fickryiman
Team member #2 : https://github.com/rbd3
Team member #3 : https://github.com/SAZZAD1Q2

**Comment by julie-ify** [comment]
## Hi, 

Good job so far!

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [ ] Kindly add a description for this task.

  ![image](https://github.com/fickryiman/Catalog-of-my-things/assets/81468675/2e9edd0f-fe97-4679-92a8-5d1c0581a0fa)

- [ ] This task does not belong to member number 1. Kindly assign your tasks correctly. Team member one is missing the required task for `can_be_archived?()` in the Book class.

  ![image](https://github.com/fickryiman/Catalog-of-my-things/assets/81468675/04b01321-a586-451a-8fae-172f3a0e9b0d)

- [ ] Team member 2 is missing this task.

  ![image](https://github.com/fickryiman/Catalog-of-my-things/assets/81468675/c9034f36-0ee8-4416-87ea-33907292fc04)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by fickryiman** [comment]
Has fulfilled all the requirements

**Comment by cynthiainga** [comment]
Hi @fickryiman, @SAZZAD1Q2 & @rbd3, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [ ] Descriptive issue ✔️ 
- [ ] All requested changes are made ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
